name: "ci-release"

on:
  push:
    tags:
      - "v*"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'zulu'

      - name: Test
        run: ./gradlew test

  release:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'zulu'
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build
        run: ./gradlew -Prelease.useLastTag=true final -x test
      
      - name: Docker
        uses: docker/build-push-action@v2
        with:
          push: true
          build-args: APP_VERSION=${GITHUB_REF##*/v}
          tags: ${{ secrets.DOCKER_REGISTRY }}/dev-school-front-app:latest,${{ secrets.DOCKER_REGISTRY }}/dev-school-front-app:${GITHUB_REF##*/v}

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: build/libs
