name: "ci-release"

on:
  push:
    tags:
      - "v*"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'zulu'

      - name: Test
        run: ./gradlew test

  release:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - id: get_version
        run: echo ::set-output name=APP_VERSION::$(echo ${GITHUB_REF##*/v})
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'zulu'
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build
        run: ./gradlew -Prelease.useLastTag=true final -x test
      
      - run: ls -la 
      - run: ls -la devschool-front-app-server
      - run: ls -la devschool-front-app-server/build
      - run: ls -la devschool-front-app-server/build/libs
      
      - name: Docker
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          build-args: APP_VERSION=${{ steps.get_version.outputs.APP_VERSION }}
          tags: ${{ secrets.DOCKER_REGISTRY }}/dev-school-front-app:latest,${{ secrets.DOCKER_REGISTRY }}/dev-school-front-app:${{ steps.get_version.outputs.APP_VERSION }}

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: build/libs
